export const fallbackProducts = [
  {
    _id: '1',
    name: 'Daily Burner Capsules',
    slug: 'daily-burner-capsules',
    description: 'A powerful daily formula to help you burn calories and manage cravings naturally.',
    price: 1249,
    originalPrice: 1599,
    images: ['/banner/product2-clean.png', '/banner/product2-nobg.png', '/banner/DailyBurner.png'],
    category: 'Daily Burner',
    benefits: ['Burn Calories', 'Reduce Carb Absorption', 'Manage Cravings', 'Boost Metabolism'],
    ingredients: ['Green Tea Extract', 'Garcinia Cambogia', 'L-Carnitine'],
    rating: 4.7,
    reviewCount: 1134,
    inStock: true,
    stockQuantity: 500,
    featured: true,
  },
  {
    _id: '2',
    name: 'Periods Pain Relief Capsule',
    slug: 'periods-pain-relief-capsule',
    description: 'Relieve menstrual discomfort naturally with our specialized pain relief formula.',
    price: 1249,
    originalPrice: 1599,
    images: ['/banner/product9-clean.png', '/banner/product9-nobg.png', '/banner/PeriodRelief.png'],
    category: 'Women Health',
    benefits: ['Relieves Cramps', 'Balances Mood', 'Reduces Inflammation', 'Hormonal Balance'],
    ingredients: ['Lodhra', 'Ashoka', 'Shatavari'],
    rating: 4.8,
    reviewCount: 945,
    inStock: true,
    stockQuantity: 500,
    featured: true,
  },
  {
    _id: '3',
    name: 'Shilajit Gummies',
    slug: 'shilajit-gummies',
    description: 'Enhance your vitality and vigor with our pure Shilajit gummies.',
    price: 1299,
    originalPrice: 1699,
    images: ['/banner/product8.png'],
    category: 'NIGHT BURNER',
    benefits: ['Enhances Vitality', 'Improves Performance', 'Boosts Energy', 'Increases Stamina'],
    ingredients: ['Shilajit Extract', 'Ashwagandha', 'Fulvic Acid'],
    rating: 4.7,
    reviewCount: 1338,
    inStock: true,
    stockQuantity: 500,
    featured: false,
  },
  {
    _id: '4',
    name: 'Beauty Gummies',
    slug: 'beauty-gummies',
    description: 'Support your hair, skin, and nails with our delicious beauty gummies.',
    price: 1249,
    originalPrice: 1599,
    images: ['/banner/product6-white.png'],
    category: 'ANYTIME BURNER',
    benefits: ['Reduce Hair Fall', 'Fade Dark Spots', 'Strengthen Hair Roots', 'Boost Skin\'s Glow'],
    ingredients: ['Biotin', 'Vitamin C', 'Vitamin E', 'Zinc'],
    rating: 4.6,
    reviewCount: 10646,
    inStock: true,
    stockQuantity: 500,
    featured: false,
  },
  {
    _id: '5',
    name: 'Sleep Gummies',
    slug: 'sleep-gummies',
    description: 'Promote sound sleep and muscle recovery with our non-habit forming melatonin gummies.',
    price: 722,
    originalPrice: 999,
    images: ['/banner/product5.jpeg'],
    category: 'Wellness',
    benefits: ['Supports Deep Sleep', 'Muscle Recovery', 'Nerve Relaxation', 'Non-Habit Forming'],
    ingredients: ['Melatonin', 'Chamomile', 'L-Theanine', 'Tart Cherry'],
    rating: 4.8,
    reviewCount: 856,
    inStock: true,
    stockQuantity: 500,
    featured: false,
  },
  {
    _id: '6',
    name: 'Stress Relief Gummies',
    slug: 'stress-relief-gummies',
    description: 'Combat stress and anxiety naturally with our strawberry-flavored calmness formula.',
    price: 722,
    originalPrice: 999,
    images: ['/banner/product6-clean.png', '/banner/product6-nobg.png', '/banner/StressRelief.png'],
    category: 'Wellness',
    benefits: ['Promotes Calmness', 'Mental Balance', 'Reduces Anxiety', 'Improves Focus'],
    ingredients: ['L-Theanine', 'Holy Basil', 'Sage Extracts', 'Passion Flower'],
    rating: 4.7,
    reviewCount: 642,
    inStock: true,
    stockQuantity: 500,
    featured: true,
  },
  {
    _id: '7',
    name: 'Gut Health Gummies',
    slug: 'gut-health-gummies',
    description: 'Balance your gut microbiome and improve digestion with our prebiotic and probiotic gummies.',
    price: 749,
    originalPrice: 1099,
    images: ['/banner/product7.jpeg'],
    category: 'Wellness',
    benefits: ['Reduces Bloating', 'Improves Digestion', 'Relieves Constipation', 'Boosts Immunity'],
    ingredients: ['Bacillus Coagulans', 'Amla Juice Powder', 'Aloe Vera Extract', 'FOS'],
    rating: 4.6,
    reviewCount: 924,
    inStock: true,
    stockQuantity: 500,
    featured: false,
  },
  {
    _id: '8',
    name: 'Gluta-Glow Gummies',
    slug: 'gluta-glow-gummies',
    description: 'Enhance your skin radiance and support liver health with liposomal glutathione.',
    price: 1049,
    originalPrice: 1499,
    images: ['/banner/product8.png'],
    category: 'Beauty',
    benefits: ['Skin Brightness', 'Evens Skin Tone', 'Liver Support', 'Collagen Production'],
    ingredients: ['Liposomal Glutathione', 'Vitamin C', 'Hyaluronic Acid', 'Vitamin E'],
    rating: 4.9,
    reviewCount: 1250,
    inStock: true,
    stockQuantity: 500,
    featured: false,
  },
  {
    _id: '9',
    name: 'Daily Burner Capsule',
    slug: 'daily-burner-capsule-2',
    description: 'Maximize your workouts and stay fit with our advanced metabolism formula.',
    price: 1099,
    originalPrice: 1599,
    images: ['/banner/product2-clean.png', '/banner/U-FIT-nobg.png', '/banner/U-FIT.png'],
    category: 'Weight Management',
    benefits: ['Boosts Metabolism', 'Increases Energy', 'Muscle Recovery', 'Weight Support'],
    ingredients: ['Green Coffee', 'L-Carnitine', 'Garcinia Cambogia'],
    rating: 4.8,
    reviewCount: 2483,
    inStock: true,
    stockQuantity: 500,
    featured: false,
  },
  {
    _id: '10',
    name: 'Night Fat Burner',
    slug: 'night-fat-burner',
    description: 'Manage cravings and burn calories while you sleep with our night-time weight formula.',
    price: 1249,
    originalPrice: 1699,
    images: ['/banner/product1-clean.png', '/banner/product1-nobg.png', '/banner/NightBurner.png'],
    category: 'Weight Management',
    benefits: ['Burn Night-time Calories', 'Manage Cravings', 'Reduces Cortisol', 'Restful Sleep'],
    ingredients: ['L-Carnitine', 'Garcinia Cambogia', 'Berberine HCl', 'Ashwagandha'],
    rating: 4.8,
    reviewCount: 730,
    inStock: true,
    stockQuantity: 500,
    featured: true,
  },
  {
    _id: '11',
    name: 'Pro Skin and Hair Combo',
    slug: 'pro-skin-hair-combo',
    description: 'Transform your skin and hair with this dermatologist-recommended combo of Beauty and Gluta-Glow supplements.',
    price: 1999,
    originalPrice: 2499,
    images: ['/banner/combo-skin-hair.jpeg'],
    category: 'Combo',
    benefits: ['Radiant Skin', 'Stronger Hair', 'Liver Support', 'Skin Brightening'],
    ingredients: ['Glutathione', 'Biotin', 'Vitamin C'],
    rating: 4.9,
    reviewCount: 450,
    inStock: true,
    stockQuantity: 200,
    featured: false,
  },
  {
    _id: '12',
    name: 'Beauty Sleep Combo',
    slug: 'beauty-sleep-combo',
    description: 'Wake up refreshed and glowing with our best-selling Beauty and Sleep combo.',
    price: 1799,
    originalPrice: 2299,
    images: ['/banner/combo-beauty-sleep.jpeg'],
    category: 'Combo',
    benefits: ['Deep Sleep', 'Hair & Skin Growth', 'Morning Glow', 'Stress Reduction'],
    ingredients: ['Melatonin', 'Biotin', 'L-Theanine'],
    rating: 4.8,
    reviewCount: 320,
    inStock: true,
    stockQuantity: 200,
    featured: false,
  },
  {
    _id: '13',
    name: 'Look Good Feel Good Combo',
    slug: 'look-good-feel-good-combo',
    description: 'The ultimate wellness bundle for your beauty, sleep, and mental peace.',
    price: 2499,
    originalPrice: 2999,
    images: ['/banner/combo-feel-good.jpeg'],
    category: 'Combo',
    benefits: ['Total Wellness', 'Anti-Stress', 'Skin Glow', 'Better Rest'],
    ingredients: ['Ashwagandha', 'Melatonin', 'Glutathione'],
    rating: 4.9,
    reviewCount: 560,
    inStock: true,
    stockQuantity: 150,
    featured: false,
  },
  {
    _id: '14',
    name: 'Stress-Free Sleep Combo',
    slug: 'stress-free-sleep-combo',
    description: 'A powerful mix to calm your mind and help you drift into a peaceful slumber.',
    price: 1399,
    originalPrice: 1799,
    images: ['/banner/Stress-Free Sleep Combo.jpeg'],
    category: 'Combo',
    benefits: ['Reduced Anxiety', 'Deeper Sleep', 'Nerve Support', 'Restorative Rest'],
    ingredients: ['L-Theanine', 'Melatonin', 'Passion Flower'],
    rating: 4.7,
    reviewCount: 290,
    inStock: true,
    stockQuantity: 300,
    featured: false,
  },
];
