export const fallbackProducts = [
  {
    _id: '1',
    name: 'U-Fit',
    slug: 'u-fit',
    description: 'A powerful formula to help you manage your fitness goals and maintain a healthy weight.',
    price: 849,
    originalPrice: 1299,
    variantPrices: {
      '1m': 849,
      '2m': 1499,
      '3m': 2100
    },
    images: ['/banner/U-F.png'],
    category: 'Weight Management',
    benefits: ['Burn Calories', 'Manage Cravings', 'Boost Metabolism'],
    ingredients: ['Green Tea Extract', 'Garcinia Cambogia', 'L-Carnitine'],
    rating: 4.7,
    reviewCount: 1134,
    inStock: true,
    stockQuantity: 500,
    featured: true,
  },
  {
    _id: '2',
    name: 'Fit Flex',
    slug: 'fit-flex',
    description: 'Enhance your flexibility and muscle recovery with our specialized Fit Flex formula.',
    price: 849,
    originalPrice: 1299,
    variantPrices: {
      '1m': 849,
      '2m': 1499,
      '3m': 2100
    },
    images: ['/banner/F-F.png'],
    category: 'Weight Management',
    benefits: ['Muscle Recovery', 'Improved Flexibility', 'Joint Support'],
    ingredients: ['Collagen', 'Glucosamine', 'Turmeric'],
    rating: 4.6,
    reviewCount: 856,
    inStock: true,
    stockQuantity: 500,
    featured: true,
  },
  {
    _id: '3',
    name: 'Period Pain Relief',
    slug: 'period-pain-relief',
    description: 'Relieve menstrual discomfort naturally with our specialized pain relief formula.',
    price: 749,
    originalPrice: 999,
    variantPrices: {
      '1m': 749,
      '2m': 1349,
      '3m': 1899
    },
    images: [
      '/banner/PeriodPainNew.png',
      '/banner/periods3.jpeg',
      '/banner/periods4.jpeg',
      '/banner/periods5.jpeg',
      '/banner/periods6.jpeg',
      '/banner/periods7.jpeg',
      '/banner/periods8.jpeg'
    ],
    category: 'Women Health',
    benefits: ['Relieves Cramps', 'Balances Mood', 'Reduces Inflammation'],
    ingredients: ['Lodhra', 'Ashoka', 'Shatavari'],
    rating: 4.8,
    reviewCount: 945,
    inStock: true,
    stockQuantity: 500,
    featured: true,
  },
  {
    _id: '4',
    name: 'Shilajit Gold',
    slug: 'shilajit-gold',
    description: 'Enhance your vitality and vigor with our pure Shilajit Gold enriched with herbal extracts.',
    price: 850,
    originalPrice: 1199,
    variantPrices: {
      '1m': 850,
      '2m': 1499,
      '3m': 2249
    },
    images: [
      '/banner/ShilajitNew.png',
      '/banner/shilijit1.jpeg',
      '/banner/shilijit2.jpeg',
      '/banner/shilijit3.jpeg',
      '/banner/shilijit4.jpeg',
      '/banner/shilijit5.jpeg'
    ],
    category: 'Performance',
    benefits: ['Enhances Vitality', 'Improves Performance', 'Boosts Energy'],
    ingredients: ['Shilajit Extract', 'Ashwagandha', 'Gold Bhasma'],
    rating: 4.7,
    reviewCount: 1338,
    inStock: true,
    stockQuantity: 500,
    featured: true,
  },
  {
    _id: '5',
    name: 'Night Relief Gummies',
    slug: 'night-relief-gummies',
    description: 'Manage stress and get restful sleep with our delicious night-time relief gummies.',
    price: 750,
    originalPrice: 1099,
    variantPrices: {
      '1m': 750,
      '2m': 1249,
      '3m': 1849
    },
    images: [
      '/banner/NightReliefNew.png',
      '/banner/nightrelief1.jpeg',
      '/banner/nightrelief2.jpeg',
      '/banner/nightrelief3.jpeg',
      '/banner/nightrelief4.jpeg',
      '/banner/nightrelief5.jpeg',
      '/banner/nightrelief6.jpeg'
    ],
    category: 'Sleep & Relaxation',
    benefits: ['Restful Sleep', 'Stress Reduction', 'Calm Mind'],
    ingredients: ['Melatonin', 'L-Theanine', 'Chamomile'],
    rating: 4.8,
    reviewCount: 730,
    inStock: true,
    stockQuantity: 500,
    featured: false,
  },
  {
    _id: '6',
    name: 'Glow Berry Gummies',
    slug: 'glow-berry-gummies',
    description: 'Support your skin glow and hair health with our delicious Glow Berry beauty gummies.',
    price: 899,
    originalPrice: 1399,
    variantPrices: {
      '1m': 899,
      '2m': 1449,
      '3m': 1979
    },
    images: ['/banner/GlowBerry.png'],
    category: 'Beauty',
    benefits: ['Skin Glow', 'Hair Strength', 'Nail Health'],
    ingredients: ['Biotin', 'Vitamin C', 'Vitamin E', 'Zinc'],
    rating: 4.6,
    reviewCount: 10646,
    inStock: true,
    stockQuantity: 500,
    featured: false,
  },
  {
    _id: '7',
    name: 'Mass Builder',
    slug: 'mass-builder',
    description: 'Build lean muscle mass and improve strength with our Mass Builder capsules.',
    price: 749,
    originalPrice: 1199,
    variantPrices: {
      '1m': 749,
      '2m': 1349,
      '3m': 1850
    },
    images: ['/banner/MassBuilder.png'],
    category: 'Muscle Gain',
    benefits: ['Muscle Growth', 'Increased Strength', 'Better Recovery'],
    ingredients: ['Whey Protein', 'Creatine', 'BCAA'],
    rating: 4.8,
    reviewCount: 320,
    inStock: true,
    stockQuantity: 200,
    featured: true,
  },
  {
    _id: '8',
    name: 'Mass Gainer Powder',
    slug: 'mass-gainer-powder',
    description: 'Get the calories you need to gain mass with our high-protein Mass Gainer powder.',
    price: 849,
    originalPrice: 1499,
    variantPrices: {
      '1m': 849,
      '2m': 1449,
      '3m': 2150
    },
    images: ['/banner/MassGainer.png'],
    category: 'Muscle Gain',
    benefits: ['Calorie Dense', 'High Protein', 'Fast Mass Gain'],
    ingredients: ['Complex Carbs', 'Protein Blend', 'Vitamins'],
    rating: 4.9,
    reviewCount: 560,
    inStock: true,
    stockQuantity: 150,
    featured: true,
  },
  {
    _id: '9',
    name: 'GutFix Health Gummies',
    slug: 'gutfix-health-gummies',
    description: 'Optimize your digestive system, ease bloating, and balance your gut microbiome with our premium probiotic-rich GutFix Health Gummies.',
    price: 899,
    originalPrice: 1399,
    variantPrices: {
      '1m': 899,
      '2m': 1599,
      '3m': 2299
    },
    images: ['/banner/GutFix.png'],
    category: 'Digestive',
    benefits: ['Balances Gut Flora', 'Improves Digestion', 'Reduces Bloating'],
    ingredients: ['Bacillus Coagulans (Probiotic)', 'Chicory Root Fiber (Prebiotic)', 'Apple Cider Vinegar'],
    rating: 4.8,
    reviewCount: 394,
    inStock: true,
    stockQuantity: 500,
    featured: true,
  },
  {
    _id: '10',
    name: 'Fit Flex & U-Fit Combo',
    slug: 'fit-flex-ufit-combo',
    description: 'Get the best of both worlds with our Fit Flex & U-Fit fitness management combo, designed to support weight loss, boost metabolism, and enhance muscle recovery.',
    price: 1399,
    originalPrice: 2598,
    variantPrices: {
      '1m': 1399,
      '2m': 2499,
      '3m': 3599
    },
    images: ['/banner/combo_fitflex_ufit.png'],
    category: 'Combo',
    benefits: ['Boost Metabolism', 'Muscle Recovery', 'Weight Management'],
    ingredients: ['L-Carnitine', 'Collagen', 'Green Tea Extract'],
    rating: 4.8,
    reviewCount: 231,
    inStock: true,
    stockQuantity: 300,
    featured: true,
  },
  {
    _id: '11',
    name: 'Glowberry & Shilajit Gold Combo',
    slug: 'glowberry-shilajit-gold-combo',
    description: 'Rejuvenate your skin and boost your daily stamina. The Glowberry & Shilajit Gold combo balances beauty with raw energy and performance.',
    price: 1449,
    originalPrice: 2598,
    variantPrices: {
      '1m': 1449,
      '2m': 2599,
      '3m': 3799
    },
    images: ['/banner/combo_glowberry_shilajit.png'],
    category: 'Combo',
    benefits: ['Skin Radiance', 'Stamina Boost', 'Vitality & Vigor'],
    ingredients: ['Biotin', 'Shilajit Extract', 'Gold Bhasma'],
    rating: 4.9,
    reviewCount: 312,
    inStock: true,
    stockQuantity: 250,
    featured: true,
  },
  {
    _id: '12',
    name: 'Mass Builder & Mass Gainer Combo',
    slug: 'mass-builder-gainer-combo',
    description: 'The ultimate muscle building package. Combines high-calorie Mass Gainer powder with Mass Builder capsules to accelerate lean muscle mass growth and strength.',
    price: 1299,
    originalPrice: 2698,
    variantPrices: {
      '1m': 1299,
      '2m': 2299,
      '3m': 3299
    },
    images: ['/banner/combo_mass_builder_gainer.png'],
    category: 'Combo',
    benefits: ['Accelerate Muscle Growth', 'Increase Strength', 'High Caloric Support'],
    ingredients: ['Whey Protein', 'Creatine', 'BCAA', 'Complex Carbs'],
    rating: 4.8,
    reviewCount: 154,
    inStock: true,
    stockQuantity: 180,
    featured: true,
  },
  {
    _id: '13',
    name: 'U-Fit & Glowberry Combo',
    slug: 'ufit-glowberry-combo',
    description: 'Manage weight while keeping your skin glowing and hair strong. A curated blend for active lifestyles and natural beauty support.',
    price: 1449,
    originalPrice: 2698,
    variantPrices: {
      '1m': 1449,
      '2m': 2599,
      '3m': 3799
    },
    images: ['/banner/combo_ufit_glowberry.png'],
    category: 'Combo',
    benefits: ['Manage Cravings', 'Skin Glow', 'Boost Metabolism'],
    ingredients: ['Garcinia Cambogia', 'Biotin', 'Vitamin C'],
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
    stockQuantity: 220,
    featured: true,
  },
  {
    _id: '14',
    name: 'Night Relief & Fit-Flex Combo',
    slug: 'night-relief-fit-flex-combo',
    description: 'Enhance your recovery overnight. Rest deeply with Night Relief Gummies and restore muscle flexibility with Fit Flex.',
    price: 1299,
    originalPrice: 2398,
    variantPrices: {
      '1m': 1299,
      '2m': 2299,
      '3m': 3299
    },
    images: ['/banner/combo_nightrelief_fitflex.png'],
    category: 'Combo',
    benefits: ['Restful Sleep', 'Muscle Recovery', 'Joint Support'],
    ingredients: ['Melatonin', 'Collagen', 'L-Theanine'],
    rating: 4.8,
    reviewCount: 176,
    inStock: true,
    stockQuantity: 200,
    featured: true,
  },
  {
    _id: '15',
    name: 'Night Relief & Glowberry Combo',
    slug: 'night-relief-glowberry-combo',
    description: 'Sleep your way to glowing skin. Support overnight cell regeneration and wake up refreshed with healthy, radiant skin and hair.',
    price: 1349,
    originalPrice: 2498,
    variantPrices: {
      '1m': 1349,
      '2m': 2399,
      '3m': 3499
    },
    images: ['/banner/combo_nightrelief_glowberry.png'],
    category: 'Combo',
    benefits: ['Cell Regeneration', 'Restful Sleep', 'Skin Glow & Hydration'],
    ingredients: ['Melatonin', 'Biotin', 'Chamomile'],
    rating: 4.9,
    reviewCount: 245,
    inStock: true,
    stockQuantity: 210,
    featured: true,
  },
  {
    _id: '16',
    name: 'U-Fit & Shilajit Gold Combo',
    slug: 'ufit-shilajit-gold-combo',
    description: 'Unleash peak fitness and high energy. U-Fit helps manage weight and fat loss while Shilajit Gold builds unmatched stamina and physical performance.',
    price: 1399,
    originalPrice: 2498,
    variantPrices: {
      '1m': 1399,
      '2m': 2499,
      '3m': 3599
    },
    images: ['/banner/combo_ufit_shilajit.png'],
    category: 'Combo',
    benefits: ['Stamina & Performance', 'Boost Metabolism', 'Weight Management'],
    ingredients: ['Green Tea Extract', 'Shilajit Extract', 'Ashwagandha'],
    rating: 4.8,
    reviewCount: 289,
    inStock: true,
    stockQuantity: 190,
    featured: true,
  },
  {
    _id: '17',
    name: 'Period Relief & Glowberry Combo',
    slug: 'period-relief-glowberry-combo',
    description: 'Designed for women\'s ultimate comfort and care. Relieve cramps and mood swings during cycles while boosting hair and skin wellness with Glowberry.',
    price: 1349,
    originalPrice: 2398,
    variantPrices: {
      '1m': 1349,
      '2m': 2399,
      '3m': 3499
    },
    images: ['/banner/combo_period_glowberry.png'],
    category: 'Combo',
    benefits: ['Relieve Cramps', 'Balance Mood', 'Skin Glow & Biotin Support'],
    ingredients: ['Lodhra', 'Biotin', 'Shatavari'],
    rating: 4.9,
    reviewCount: 167,
    inStock: true,
    stockQuantity: 240,
    featured: true,
  },
  {
    _id: '18',
    name: 'Mass Builder & Glowberry Combo',
    slug: 'mass-builder-glowberry-combo',
    description: 'Build a toned body and maintain natural beauty. Combines muscle growth capsules with skin & hair building biotin gummies.',
    price: 1349,
    originalPrice: 2598,
    variantPrices: {
      '1m': 1349,
      '2m': 2399,
      '3m': 3499
    },
    images: ['/banner/combo_massbuilder_glowberry.png'],
    category: 'Combo',
    benefits: ['Muscle Tone', 'Skin Glow', 'Nail & Hair Strength'],
    ingredients: ['Whey Protein', 'Biotin', 'BCAA'],
    rating: 4.7,
    reviewCount: 112,
    inStock: true,
    stockQuantity: 150,
    featured: true,
  },
  {
    _id: '19',
    name: 'Mass Gainer & Shilajit Gold Combo',
    slug: 'mass-gainer-shilajit-gold-combo',
    description: 'The ultimate performance and size bundle. High protein mass gainer powder paired with premium Shilajit Gold to maximize strength, power output, and muscle volume.',
    price: 1399,
    originalPrice: 2698,
    variantPrices: {
      '1m': 1399,
      '2m': 2499,
      '3m': 3599
    },
    images: ['/banner/combo_massgainer_shilajit.png'],
    category: 'Combo',
    benefits: ['Maximize Strength', 'Stamina & Performance', 'Massive Calorie Support'],
    ingredients: ['Complex Carbs', 'Shilajit Extract', 'Gold Bhasma'],
    rating: 4.9,
    reviewCount: 343,
    inStock: true,
    stockQuantity: 130,
    featured: true,
  },
];
