export const fallbackProducts = [
  {
    _id: '1',
    name: 'Daily Burner Capsules',
    slug: 'daily-burner-capsules',
    description: 'A powerful daily formula to help you burn calories and manage cravings naturally.',
    price: 1249,
    originalPrice: 1599,
    images: ['/banner/product2-clean.png', '/banner/product2-nobg.png', '/banner/DailyBurner.png'],
    category: 'Daily Burner',
    benefits: ['Burn Calories', 'Reduce Carb Absorption', 'Manage Cravings', 'Boost Metabolism'],
    ingredients: ['Green Tea Extract', 'Garcinia Cambogia', 'L-Carnitine'],
    rating: 4.7,
    reviewCount: 1134,
    inStock: true,
    stockQuantity: 500,
    featured: true,
  },
  {
    _id: '2',
    name: 'Periods Pain Relief Capsule',
    slug: 'periods-pain-relief-capsule',
    description: 'Relieve menstrual discomfort naturally with our specialized pain relief formula.',
    price: 1249,
    originalPrice: 1599,
    images: ['/banner/product9-clean.png', '/banner/product9-nobg.png', '/banner/PeriodRelief.png'],
    category: 'Women Health',
    benefits: ['Relieves Cramps', 'Balances Mood', 'Reduces Inflammation', 'Hormonal Balance'],
    ingredients: ['Lodhra', 'Ashoka', 'Shatavari'],
    rating: 4.8,
    reviewCount: 945,
    inStock: true,
    stockQuantity: 500,
    featured: true,
  },
  {
    _id: '3',
    name: 'Shilajit Gummies',
    slug: 'shilajit-gummies',
    description: 'Enhance your vitality and vigor with our pure Shilajit gummies.',
    price: 1299,
    originalPrice: 1699,
    images: ['/banner/product8.png'],
    category: 'NIGHT BURNER',
    benefits: ['Enhances Vitality', 'Improves Performance', 'Boosts Energy', 'Increases Stamina'],
    ingredients: ['Shilajit Extract', 'Ashwagandha', 'Fulvic Acid'],
    rating: 4.7,
    reviewCount: 1338,
    inStock: true,
    stockQuantity: 500,
    featured: false,
  },
  {
    _id: '4',
    name: 'Beauty Gummies',
    slug: 'beauty-gummies',
    description: 'Support your hair, skin, and nails with our delicious beauty gummies.',
    price: 1249,
    originalPrice: 1599,
    images: ['/banner/product6-white.png'],
    category: 'ANYTIME BURNER',
    benefits: ['Reduce Hair Fall', 'Fade Dark Spots', 'Strengthen Hair Roots', 'Boost Skin\'s Glow'],
    ingredients: ['Biotin', 'Vitamin C', 'Vitamin E', 'Zinc'],
    rating: 4.6,
    reviewCount: 10646,
    inStock: true,
    stockQuantity: 500,
    featured: false,
  },
  {
    _id: '5',
    name: 'Sleep Gummies',
    slug: 'sleep-gummies',
    description: 'Promote sound sleep and muscle recovery with our non-habit forming melatonin gummies.',
    price: 722,
    originalPrice: 999,
    images: ['/banner/product5.jpeg'],
    category: 'Wellness',
    benefits: ['Supports Deep Sleep', 'Muscle Recovery', 'Nerve Relaxation', 'Non-Habit Forming'],
    ingredients: ['Melatonin', 'Chamomile', 'L-Theanine', 'Tart Cherry'],
    rating: 4.8,
    reviewCount: 856,
    inStock: true,
    stockQuantity: 500,
    featured: false,
  },
  {
    _id: '7',
    name: 'Gut Health Gummies',
    slug: 'gut-health-gummies',
    description: 'Balance your gut microbiome and improve digestion with our prebiotic and probiotic gummies.',
    price: 749,
    originalPrice: 1099,
    images: ['/banner/product7.jpeg'],
    category: 'Wellness',
    benefits: ['Reduces Bloating', 'Improves Digestion', 'Relieves Constipation', 'Boosts Immunity'],
    ingredients: ['Bacillus Coagulans', 'Amla Juice Powder', 'Aloe Vera Extract', 'FOS'],
    rating: 4.6,
    reviewCount: 924,
    inStock: true,
    stockQuantity: 500,
    featured: false,
  },
  {
    _id: '9',
    name: 'Daily Burner Capsule',
    slug: 'daily-burner-capsule-2',
    description: 'Maximize your workouts and stay fit with our advanced metabolism formula.',
    price: 1099,
    originalPrice: 1599,
    images: ['/banner/product2-clean.png', '/banner/U-FIT-nobg.png', '/banner/U-FIT.png'],
    category: 'Weight Management',
    benefits: ['Boosts Metabolism', 'Increases Energy', 'Muscle Recovery', 'Weight Support'],
    ingredients: ['Green Coffee', 'L-Carnitine', 'Garcinia Cambogia'],
    rating: 4.8,
    reviewCount: 2483,
    inStock: true,
    stockQuantity: 500,
    featured: false,
  },
  {
    _id: '10',
    name: 'Night Fat Burner',
    slug: 'night-fat-burner',
    description: 'Manage cravings and burn calories while you sleep with our night-time weight formula.',
    price: 1249,
    originalPrice: 1699,
    images: ['/banner/product1-clean.png', '/banner/product1-nobg.png', '/banner/NightBurner.png'],
    category: 'Weight Management',
    benefits: ['Burn Night-time Calories', 'Manage Cravings', 'Reduces Cortisol', 'Restful Sleep'],
    ingredients: ['L-Carnitine', 'Garcinia Cambogia', 'Berberine HCl', 'Ashwagandha'],
    rating: 4.8,
    reviewCount: 730,
    inStock: true,
    stockQuantity: 500,
    featured: true,
  },
  {
    _id: '12',
    name: 'MASS GAINER & BUILDER COMBO',
    slug: 'mass-gainer-builder-combo',
    description: 'Wake up refreshed and glowing with our best-selling Beauty and Sleep combo.',
    price: 1799,
    originalPrice: 2299,
    images: ['/banner/combo-beauty-sleep.jpeg'],
    category: 'Combo',
    benefits: ['Deep Sleep', 'Hair & Skin Growth', 'Morning Glow', 'Stress Reduction'],
    ingredients: ['Melatonin', 'Biotin', 'L-Theanine'],
    rating: 4.8,
    reviewCount: 320,
    inStock: true,
    stockQuantity: 200,
    featured: false,
  },
  {
    _id: '13',
    name: 'Shilajit and Beauty Gummies Combo',
    slug: 'shilajit-beauty-gummies-combo',
    description: 'The ultimate wellness bundle for your beauty, sleep, and mental peace.',
    price: 2499,
    originalPrice: 2999,
    images: ['/banner/combo-feel-good.jpeg'],
    category: 'Combo',
    benefits: ['Total Wellness', 'Anti-Stress', 'Skin Glow', 'Better Rest'],
    ingredients: ['Ashwagandha', 'Melatonin', 'Glutathione'],
    rating: 4.9,
    reviewCount: 560,
    inStock: true,
    stockQuantity: 150,
    featured: false,
  },
];
